schema_version = "1.0.0"
id = "quick_sidebar_switcher"
version = "1.3.0"
name = "Quick Sidebar Switcher"
tagline = "Quickly switch between Side Panel tabs with a popup menu"
maintainer = "hyeffect55 <hyeffect55@gmail.com>"
type = "add-on"
wetsite = "https://github.com/juhoyoung/Quick-Sidebar-Switcher"
support = "https://github.com/juhoyoung/Quick-Sidebar-Switcher/issues/new"

blender_version_min = "5.0.1"
license = ["SPDX:GPL-3.0-or-later"]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".*",
  "*.zip",
  "*.sh"
]